import Head from 'next/head'
import { Open_Sans } from 'next/font/google'
import Menu from '@/components/Menu'

const inter = Open_Sans({ subsets: ['latin'] })

export default function Home() {
    return (
        <>
            <Head>
                <title>DIO</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                <Menu />
            </main>
        </>
    )
}
