import styles from '../styles/Home.module.scss'

import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Open_Sans } from 'next/font/google'

import Layout from '@/components/Layout'
import CheckRoute from '@/components/CheckRoute'

const inter = Open_Sans({ subsets: ['latin'] })

export default function App() {
    return (
        <CheckRoute admin={false}>
            <Head>
                <title>DIO</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={inter.className}>
                <Layout>
                    <div className={styles.container}>
                        <div className={styles.content}>
                            <h1>Implemente</h1>
                            <h2>o seu futuro global agora!</h2>
                            <p>
                                Domine as tecnologias utilizadas pelas empresas
                                mais inovadoras do mundo e encare seu novo
                                desafio profissional, evoluindo em comunidade
                                com os melhores experts.
                            </p>
                            <div className={styles.btn}>
                                <Link href={'/autenticacao'}>
                                    <button>Começar agora</button>
                                </Link>
                            </div>
                        </div>
                        <Image
                            className={styles.img}
                            src="/home.png"
                            alt="Tecnologia"
                            width={0}
                            height={0}
                            sizes="100vw"
                        />
                    </div>
                </Layout>
            </main>
        </CheckRoute>
    )
}
